### ISSUE TITLE
metadata.xml is not up-to-date in central repository

### ISSUE THREAD

**Issue by BigMichi1** [forge/roaster#204]
as we use multiple plugins to detect newer versions of used libraries we figured out that updates were not suggested for the roaster libraries. by digging a little bit deeper into that we noticed that the `metadata.xml` file in the central repository (https://repo1.maven.org/maven2/org/jboss/forge/roaster/roaster-api/maven-metadata.xml) lists as the last version `2.17.4.Final` and was last updated December 2015.

can this pls be fixed when a new release is uploaded to the central repository to also update the `metadata.xml` file?

**Comment by gastaldi** [comment]
We don't control that, really, it's up to Sonatype to perform that when synchronizing to central.

**Comment by BigMichi1** [comment]
is there something (getting in contact with Sonatype to maybe check whats wrong) we, or you can do here?

**Comment by gastaldi** [comment]
@BigMichi1 I can try performing a new release if that helps. Let me give it a shot

**Comment by gastaldi** [comment]
Looks like it works now: https://repo1.maven.org/maven2/org/jboss/forge/roaster/roaster-api/maven-metadata.xml

**Comment by BigMichi1** [comment]
strange, checked t now and i see still the old version of the metadata file, checked via multiple pcs and internet providers to avoid some caching problems
![Bildschirmfoto vom 2021-09-15 07-46-10](https://user-images.githubusercontent.com/91786/133377651-b15f5f72-6652-4535-8f09-963b373c6453.png)

**Comment by gastaldi** [comment]
That's really weird, I could swear it was updated yesterday. Let me perform a new release, now with an updated JDT

**Comment by gastaldi** [comment]
There you go, let's see if that changes tomorrow: 

![Screenshot from 2021-09-15 12-47-14](https://user-images.githubusercontent.com/54133/133466149-cbbded5f-b10e-4466-b0d8-417b06df8747.png)

**Comment by BigMichi1** [comment]
checked now, and we are back with the old metadata file, same one as I posted yesterday

**Comment by gastaldi** [comment]
I created a ticket in https://issues.sonatype.org/browse/MVNCENTRAL-6967 asking for someone in Sonatype to verify what's going on. Thanks for the feedback!

**Comment by gastaldi** [comment]
@BigMichi1 now it should be fixed permanently! Sorry for the trouble

**Comment by BigMichi1** [comment]
thx,works fine now
