### ISSUE TITLE
Support nested types in Records

### ISSUE THREAD

**Issue by pcimcioch** [forge/roaster#262]
It would be useful if `JavaRecordSource` could have `addNestedType` method.
Such method is already present in `JavaClassSource`

**Comment by gastaldi** [comment]
@pcimcioch good idea! I created https://github.com/forge/roaster/pull/263 introducing it

**Comment by pcimcioch** [comment]
Wow, that was fast! Do you have a release schedule?

**Comment by gastaldi** [comment]
I'll verify some other issues and release once the fixes are integrated
