### ISSUE TITLE
LGPL license on a source file

### ISSUE THREAD

**Issue by hyandell** [forge/roaster#305]
Hi Roaster folk,

I noticed that the file https://github.com/forge/roaster/blob/master/tests/src/test/resources/org/jboss/forge/grammar/java/BigInterface.java has an LGPL-2.1 header, which seems out of sorts with the overall Eclipse-2.0 licensing of the rest of the project.

Is this an error, or was it intended?

**Comment by gastaldi** [comment]
Hi,

I believe this was copied from some other class that was LGPL, so we just kept the headers. Since it's used in tests only, there isn't a strong reason to change it, but feel free to submit a PR if you think it shouldn't and I'll gladly review it

**Comment by hyandell** [comment]
Thanks for the review & reply George.

If Red Hat/JBoss have the permissions to relicense, I'd encourage it to keep things simple. Your point that it's only on the tests is a good one though, so I think it's more about stopping others spending time investigating the licensing oddity.
