### ISSUE TITLE
Bug in FieldImpl.getName() Method: Incorrect Handling of Multiple Variables in One Line

### ISSUE THREAD

**Issue by alivny** [forge/roaster#339]
We have encountered a bug in the getName() method of the FieldImpl class in the Roaster library version 2.28.0.Final. When multiple variable declarations are made on the same line (e.g., String a, b;), the method returns the name of the first variable (a) for both variables instead of returning the correct name (b) for the second variable.

**steps to reproduce:** 

JavaType<?> javaType = Roaster.parse(MultipleFieldDeclarationDataObject);

if (javaType instanceof FieldHolderSource) {
    FieldHolderSource<?> fieldHolderSource = (FieldHolderSource<?>) javaType;
     fieldHolderSource.getFields().forEach(f -> System.out.println(f.getName()));
}
            
**Environment:**            

Roaster Version: 2.28.0.Final
Java Version: 11 (Although we know newer versions support Java 17, we need a fix that remains compatible with Java 11)

This issue is urgent because it affects our application's core functionality in production. We ask for your quick attention.

Thanks in advance.

[MultipleFieldDeclarationDataObject.txt](https://github.com/user-attachments/files/18092584/MultipleFieldDeclarationDataObject.txt)

**Comment by gastaldi** [comment]
Thanks for the report!

Roaster requires Java 17 because Eclipse JDT (the library it depends on) requires JDK 17, that's why we can't build Roaster with JDK 11.

I can have a look, but if you could provide the fix in a pull request (with a test demonstrating the bug) it would be easier

**Comment by gastaldi** [comment]
The fix is now in 2.28.1.Final and 2.30.1.Final. Enjoy!

**Comment by alivny** [comment]
@gastaldi  Thank you for the prompt fix and release. However, I encountered a couple of issues:
1. Version 2.28.1.Final is incompatible with Java 11 as it fails during compilation, requiring JDK 17.
2. I was unable to locate version 2.30.1.Final during my project build. Additionally, this version is absent from the following repository:
https://artifact.intuit.com/artifactory/maven-proxy-new/org/jboss/forge/roaster/roaster-api/

**Comment by gastaldi** [comment]
@alivny thanks for your feedback. In fact Eclipse uses ranged versions, which makes it impossible to create reproducible builds. I've fixed that in https://github.com/forge/roaster/commit/145d9145802e64cef2c92f717249f5d2b94b1771 and released `2.28.2.Final`.

Also 2.30.1.Final is now available, Maven central was unstable yesterday
